service:
  name: nestjs-serverless

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    FIGHTERS_TABLE_NAME: ${self:custom.FightersTable.name}
    DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodbURL}

resources:
  FightersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FightersTable-${self:provider.stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  FightersTable:
    name: !Ref FightersTable
    arn: !GetAtt FightersTable.Arn
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      migrate: true
  endpoints:
    dynamodbURL: 'http://localhost:8000'

package:
  excludeDevDependencies: true
